# Generated by Django 5.0.7 on 2024-08-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0002_courserating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gif_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
