# Generated by Django 5.0.7 on 2024-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0003_course_gif_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_text', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.URLField()),
            ],
        ),
    ]
