# Generated by Django 5.0.7 on 2024-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0004_demorequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('title2', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('placeholder_email', models.EmailField(max_length=254)),
                ('button_text', models.CharField(max_length=50)),
                ('popular_blog_title', models.CharField(max_length=50)),
                ('popular_blog_mini_title', models.TextField()),
                ('blog_author', models.TextField()),
                ('publish_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('quote', models.TextField()),
                ('content_description', models.TextField()),
                ('advertisement', models.ImageField(upload_to='')),
            ],
        ),
    ]
