# Generated by Django 5.0.7 on 2024-09-03 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0005_backgroundcontent_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackgroundContent',
            new_name='Blog_List',
        ),
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog_Page',
        ),
    ]
