# Generated by Django 5.0.7 on 2024-09-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0006_rename_backgroundcontent_blog_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_list',
            name='background_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
