# Generated by Django 5.0.7 on 2024-09-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0007_blog_list_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommended_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('point1', models.CharField(max_length=50)),
                ('point2', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=50)),
            ],
        ),
    ]
