# Generated by Django 5.0.7 on 2024-09-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0008_recommended_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recommended_courses',
            new_name='recommended_course',
        ),
    ]
