# Generated by Django 5.0.7 on 2024-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0009_rename_recommended_courses_recommended_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended_course',
            name='point1',
            field=models.CharField(max_length=150),
        ),
    ]
