# Generated by Django 5.0.7 on 2024-09-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0010_alter_recommended_course_point1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommended_course',
            name='point2',
            field=models.CharField(max_length=150),
        ),
    ]
