# Generated by Django 5.0.7 on 2024-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataworks_app', '0011_alter_recommended_course_point2'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='header_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
